### ISSUE TITLE
Enhance foods route

### ISSUE THREAD

**Issue by martincserep** [martincserep/orderz-backend#4]
**Tasks**
- [ ] Get all foods
- [ ] Get foods by category
- [ ] Get food by id
- [ ] Add food
- [ ] Delete food
- [ ] Edit food
