### ISSUE TITLE
Enhance cart route

### ISSUE THREAD

**Issue by martincserep** [martincserep/orderz-backend#5]
**Tasks**
- [ ] Add food to cart
- [ ] Delete food from cart
- [ ] Edit food amount in cart
- [ ] Get all carts
- [ ] Get fulfilled carts
- [ ] Get not fulfilled carts
